### ISSUE TITLE
Use systemd in Rhel/Centos 7?

### ISSUE THREAD

**Issue by linbo** [openresty/openresty-packaging#18]
Hi,

I check Rhel/Centos 7 rpm package, looks it use /etc/init.d, not systemd. Any plan to use systemd?

**Comment by agentzh** [comment]
@linbo You should always roll out your own systemd scripts. Since there might be multiple different OpenResty applications running in the same system anyway. And you should always use the `-p PATH` option to start OpenResty with your own application's directory. The bundled `init` script is just for demonstration and testing purposes.
